config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  
  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:create, :edit, :update]
  resources :messages, only: [:create]

  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user

  validates :body, presence: true

  scope :last_twenty, -> { order(:created_at).last(20) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :messages

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_user
    redirect_to login_path, alert: 'You must be logged in to perform that.' unless logged_in?
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @users = User.all
    @messages = Message.last_twenty
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_user

  def create
    @message = current_user.messages.new(message_params)

    if @message.save
      ActionCable.server.broadcast 'chatroom_channel', mod_message: message_render(@message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(msg)
    render(partial: 'message', locals: { message: msg })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_redirect, except: [:destroy]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])

    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You have successfully logged in.'
    else
      flash.now[:alert] = 'There was something wrong with your login information.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have logged out.'
  end

  private

  def logged_in_redirect
    redirect_to root_path, alert: 'You are already logged in.' if logged_in?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]
  before_action :require_owner, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome to message me #{@user.username}."
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Account successfully updated.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def require_owner
    unless current_user == User.find(params[:id])
      redirect_to root_path, alert: 'You can only edit your own account.'
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_messages
    classes = {
      'notice' => 'success',
      'alert' => 'negative'
    }

    render 'layouts/flash_message', alert_classes: classes
  end
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular coffee blue inverted icon"></i>
  Message Me
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content", id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: 'ui reply form', role: 'form' }, 
          url: messages_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'enter a message...' %>
              <%= f.button '<i class="bordered blue edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <% @users.each do |user| %>
            <%= link_to user.username, '#', 
              class: "item #{'active blue' if user == current_user}" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="ui <%= alert_classes[type] %> message transitions">
    <div class="header">
      <%= message %>
    </div>
    <i class="close icon"></i>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui small blue inverted menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path, class: 'item' %>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log out', session_path(current_user), method: :delete, class: 'item' %>
            <%= link_to 'Edit your account', edit_user_path(current_user), class: 'item' %>
          <% else %>
            <%= link_to 'Log in', login_path, class: 'item' %>
          <% end %>
        </div>
      </div>
      <% unless logged_in? %>
        <div class="item">
          <%= link_to 'Sign up', signup_path, class: 'ui violet button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe1</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="ui grid">
  <div class="eight wide column centered">
    <% if @user.errors.any? %>
      <div class="ui error message">
        <i class="close icon"></i>
        <div class="header">
          You got these errors:
        </div>
        <ul class="list">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
    <div class="ui form">
      <%= form_for @user do |f| %>
        <div class="field">
          <%= f.text_field :username, placeholder: 'username', type: 'text', focus: true %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: 'password' %>
        </div>
        <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: 'ui button violet') %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="center">Edit yout account:</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="center">Sign up for Message Me</h1>

<%= render 'form' %>